server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
  username: ${POSTGRES_USER:root}
  password: ${POSTGRES_PASSWORD:root}

---

spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test